### ISSUE TITLE
Issues with Visual C++ compiler

### ISSUE THREAD

**Issue by KindDragon** [facebook/folly#677]
- [x] [folly/Malloc.h(193)](https://github.com/facebook/folly/blob/271977282fe30d3c351b5e8a6f1692d743996ed1/folly/Malloc.h#L193): error C2059: syntax error: 'volatile'  PR #688
- [x] [folly/detail/Crc32cDetail.cpp(208)](https://github.com/facebook/folly/blob/271977282fe30d3c351b5e8a6f1692d743996ed1/folly/detail/Crc32cDetail.cpp#L208): [fatal error C1009: compiler limit: macros nested too deeply](https://github.com/facebook/folly/commit/74102328f60e450de7d1dab40d1772f82549fd96#commitcomment-23423375)
- [x] [folly/executors/NamedThreadFactory.h(38)](https://github.com/facebook/folly/blob/271977282fe30d3c351b5e8a6f1692d743996ed1/folly/executors/NamedThreadFactory.h#L37-L38): error C2665: 'folly::setThreadName': none of the 2 overloads could convert all the argument types
- [x] folly can't link with static libraries https://gist.github.com/KindDragon/c4e6414bd60242d317bb0387a82dce61#file-package-x64-windows-static-rel-out-log-L2291 PR #693
- [x] [folly/futures/Future-inl.h(242)](https://github.com/facebook/folly/blob/fbc4c23895b0ee3874d9a36401d580a2a8957ba9/folly/futures/Future-inl.h#L242): error C2244: 'folly::SemiFuture<T>::SemiFuture': unable to match function definition to an existing declaration
- [x] [folly/io/async/AsyncSocket.cpp(1589)](https://github.com/facebook/folly/blob/1b0dfd663244c1d743052072a507f1b9e1f88d05/folly/io/async/AsyncSocket.cpp#L1589): error C2039: 'Control': is not a member of 'msghdr'. Win10 SDK define MSG_ERRQUEUE too https://naughter.wordpress.com/2017/07/16/changes-in-the-windows-v10-0-16232-sdk-compared-to-windows-v10-0-15063-sdk-part-one/ PR #689
- [x] [folly/io/async/AsyncSocket.cpp(939)](https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSocket.cpp#L937-L946): error C2065: 'SOL_IP': undeclared identifier
- [x] [folly/stats/Histogram.cpp(43)](https://github.com/facebook/folly/blob/1b0dfd663244c1d743052072a507f1b9e1f88d05/folly/stats/Histogram.cpp#L38-L43): error C5037: 'folly::detail::HistogramBuckets<__int64,folly::detail::Bucket<T>>::getPercentileBucketIdx': an out-of-line definition of a member of a class template cannot have default arguments with [T=int64_t] MSVC 2017U4 PR #691
- [x] [folly/synchronization/CallOnce.h(86)](https://github.com/facebook/folly/blob/a447cb9ebc32100b18c0e3fc75bf5882db4857e3/folly/synchronization/CallOnce.h#L86): error C2988: unrecognizable template declaration/definition. CallOnce.h(98): note: see reference to class template instantiation 'folly::detail::once_flag<Mutex>' being compiled https://github.com/facebook/folly/commit/b529367b595dd4da7e70569cbea36d30ace4fa39#commitcomment-25665382
- [x] [folly\Random.cpp(43)](https://github.com/facebook/folly/blob/a447cb9ebc32100b18c0e3fc75bf5882db4857e3/folly/Random.cpp#L43): error C2672: 'folly::detail::once_flag<folly::SharedMutex>::{dtor}': no matching overloaded function found
- [x] [GroupVarint.cpp(134)](https://github.com/facebook/folly/blob/fe3444b4637beb5d2bb59371cd49e34dadcd12b6/folly/GroupVarint.cpp#L134): error C2370: 'folly::detail::groupVarintSSEMasks': redefinition; different storage class
- [x] [Format.cpp(82)](https://github.com/facebook/folly/blob/fe3444b4637beb5d2bb59371cd49e34dadcd12b6/folly/Format.cpp#L82-L83): error C2370: 'folly::detail::formatHexLower': redefinition; different storage class. Same on lines 84, 86, 88
- [x] Futex.h(47): error C2039: 'Atom': is not a member of 'std::atomic<unsigned int>' https://ci.appveyor.com/project/KindDragon/folly/build/20/job/p3kt29bxfggn3ib7#L251
- [x] AsyncSocket.cpp(986): error C3861: 'BOOST_PP_IIF_BOOST_PP_BOOL_FOLLY_HAVE_VLA': identifier not found https://ci.appveyor.com/project/KindDragon/folly/build/31/job/45bx663tx1m62n8k#L3198
- [x] Rcu code crash at exit
- [x] VS2015 [folly/ConstexprMath.h(57)](https://github.com/facebook/folly/blob/0893755f0b985d4dd9dc44420f49a27878cd774c/folly/ConstexprMath.h#L57): error C3250: 'folly::constexpr_clamp::Less': declaration is not allowed in 'constexpr' function body

/cc @Orvid

**Comment by capsocrates** [comment]
Here's another one that's more subtle... this line in the compiler (see hyperlink):
[`    return abspath.string();`](https://github.com/facebook/fbthrift/blob/0da39a12b753e64698e5aae8b270a6bedd3f1ec2/thrift/compiler/common.cc#L142)
Does not normalize `\` vs. `/` on Windows, which can generate invalid paths with mixed `\`s and `/`s depending on the user's input. The ultimate behavior is that no files are generated, but there is also no error. I had to step into the debugger to figure out what was going wrong.

Using `.generic_string()` instead of `.string()` should solve the problem for Windows without breaking `*nix` builds (where the two methods [give the same output](http://www.boost.org/doc/libs/1_62_0/libs/filesystem/doc/reference.html#path-decomposition-table)).

**Comment by capsocrates** [comment]
I previously covered the third issue [here](https://github.com/facebook/folly/issues/674).

**Comment by capsocrates** [comment]
Here's another one: https://github.com/facebook/folly/issues/679

**Comment by Orvid** [comment]
With the static libraries issue, it looks like there's a mismatch in which CRT the various libraries are being linked against. Folly itself looks like it's being linked against the static CRT, but `gflags_static.lib` has been compiled against the dynamic CRT.

**Comment by KindDragon** [comment]
Thanks with static libraries issue

**Comment by nikkov** [comment]
In addition to errors above, build vcpkg and master branch with VS2015.3 failed with error "IPAddressV6.cpp(421): error C2666: inet_ntop: 2 overloads have similar conversions" . 
Variants: 
PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t) or 
const char *folly::portability::sockets::inet_ntop(int,const void *,char *,socklen_t)

**Comment by Orvid** [comment]
Where is the `inet_ntop` you are seeing defined? It's not part of the normal Windows SDK as far as I'm aware.

**Comment by nikkov** [comment]
In my environment "PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)" defined in C:\Program Files (x86)\Windows Kits\8.1\include\um\WS2tcpip.h(576) and in my case it's default settings in VS2015.

Maybe this is my special case, but it can be quickly and safely fixed - just add full name: folly::portability::sockets::inet_ntop

**Comment by akrieger** [comment]
https://github.com/facebook/folly/commit/ca0e432d0fbd3140e4eb172641588ffdbe30b439 addresses the issue with the SemiFuture constructor.

**Comment by KindDragon** [comment]
@akrieger Thanks

**Comment by KindDragon** [comment]
@djwatson @Orvid Hi. After commit f885995c00a27e0e440c0e5cb66ec3298fc507d4 generate_fingerprint_tables.exe crash when it exits on destruction [`rcu_default_domain_`](https://github.com/facebook/folly/blob/f885995c00a27e0e440c0e5cb66ec3298fc507d4/folly/synchronization/Rcu.cpp#L20)

**Comment by Orvid** [comment]
Yep, I've noticed. After a recent change, rcu has data in thread_local storage, but the portability implementation of pthread thread-local data is also backed by `thread_local` storage. The issue is that the portability implementation's data is being destroyed before rcu's data :(

**Comment by KindDragon** [comment]
I think we can temporarily disable Rcu code for VC++, before we find how to fix it

**Comment by Orvid** [comment]
I've already re-written the code backing the pthread portability implementation to use Boost instead, which handles lifetimes better and fixes the issue.

**Comment by KindDragon** [comment]
BTW after building Folly without RCU, generate_fingerprint_tables.exe crash for me inside gflags dll

**Comment by Orvid** [comment]
https://github.com/facebook/folly/commit/fe4fcdc95f3640d5d87d130988322c50147ae638 fixes the RCU issue :)

**Comment by yfeldblum** [comment]
Which of these are still issues?

**Comment by KindDragon** [comment]
> Which of these are still issues?

VS2015 folly/ConstexprMath.h(57): error C3250: 'folly::constexpr_clamp::Less': declaration is not allowed in 'constexpr' function body

**Comment by yfeldblum** [comment]
@KindDragon - that one should be fixed in 66405fc6fea124830bcb337c9e93ed7ca35ba830 (plus 0e169ccf37b1d62c79144d5e624efd7777182a20), right?

**Comment by KindDragon** [comment]
I will check

**Comment by KindDragon** [comment]
@yfeldblum Yes, everything works. Thanks
